"""empty message

Revision ID: 0d06bf7fbf9d
Revises: 636ac6ddf172
Create Date: 2024-12-20 20:18:51.385795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d06bf7fbf9d'
down_revision = '636ac6ddf172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alojamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.Integer(), nullable=False),
    sa.Column('estado_finca', sa.String(length=100), nullable=False),
    sa.Column('clase_finca', sa.String(length=100), nullable=False),
    sa.Column('finca_nombre', sa.String(length=200), nullable=False),
    sa.Column('domicilio', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medios_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_medio_pago', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('codigo_secreto', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta1', sa.String(length=500), nullable=False),
    sa.Column('pregunta2', sa.String(length=500), nullable=False),
    sa.Column('pregunta10', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=False),
    sa.Column('domicilio', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_transaccion', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_res', sa.Integer(), nullable=False),
    sa.Column('fecha_res', sa.Date(), nullable=False),
    sa.Column('fecha_ini', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alojamiento_id', sa.Integer(), nullable=False),
    sa.Column('medio_pago_id', sa.Integer(), nullable=False),
    sa.Column('transaccion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alojamiento_id'], ['alojamientos.id'], ),
    sa.ForeignKeyConstraint(['medio_pago_id'], ['medios_pago.id'], ),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transacciones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaccion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transacciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardia_civil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_database.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.drop_table('guardia_civil')
    op.drop_table('tipo_transacciones')
    op.drop_table('reservas')
    op.drop_table('transacciones')
    op.drop_table('qr_database')
    op.drop_table('empresa')
    op.drop_table('preguntas')
    op.drop_table('medios_pago')
    op.drop_table('alojamientos')
    # ### end Alembic commands ###
