"""empty message

Revision ID: 136f80adf8ea
Revises: 29d7e6de8539
Create Date: 2025-01-15 17:59:33.796068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136f80adf8ea'
down_revision = '29d7e6de8539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
