"""empty message

Revision ID: 5579ee094f67
Revises: 78ff76c19a8f
Create Date: 2025-01-30 16:33:56.943821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5579ee094f67'
down_revision = '78ff76c19a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('group_contact_id_fkey', type_='foreignkey')
        batch_op.drop_column('contact_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('group_contact_id_fkey', 'contact', ['contact_id'], ['id'])

    # ### end Alembic commands ###
