"""empty message

Revision ID: 651742744529
Revises: 64b69605d490
Create Date: 2025-01-29 18:28:27.771004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651742744529'
down_revision = '64b69605d490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('medio_pago_nro',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=19),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('medio_pago_nro',
               existing_type=sa.String(length=19),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
