"""empty message

Revision ID: a1235fceea47
Revises: 636ac6ddf172
Create Date: 2024-12-28 18:10:14.796738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1235fceea47'
down_revision = '636ac6ddf172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_viajero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('primer_apellido', sa.String(length=100), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=100), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=False),
    sa.Column('numero_soporte_documento', sa.String(length=20), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=False),
    sa.Column('nacionalidad', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('localidad', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('telefono_fijo', sa.String(length=20), nullable=True),
    sa.Column('telefono_movil', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('numero_viajeros', sa.Integer(), nullable=False),
    sa.Column('parentesco_viajeros', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datos_viajero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datos_viajero_nif'), ['nif'], unique=True)

    op.create_table('qr_database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viajero_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=False),
    sa.Column('fecha_transaccion', sa.Date(), nullable=False),
    sa.Column('firmas', sa.String(length=100), nullable=False),
    sa.Column('fecha_hora_entrada', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_salida', sa.DateTime(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('numero_habitaciones', sa.Integer(), nullable=False),
    sa.Column('conexion_internet', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('identificacion_medio_pago', sa.String(length=100), nullable=False),
    sa.Column('titular_medio_pago', sa.String(length=100), nullable=False),
    sa.Column('fecha_caducidad_tarjeta', sa.Date(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['viajero_id'], ['datos_viajero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaccion_referencia'), ['referencia'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaccion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaccion_referencia'))

    op.drop_table('transaccion')
    op.drop_table('qr_database')
    with op.batch_alter_table('datos_viajero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datos_viajero_nif'))

    op.drop_table('datos_viajero')
    # ### end Alembic commands ###
